routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('messages')->name('messages.')->group(function () {
    Route::get('/config', 'xsoft\messages\MainMessageController@messagesConfig')->name('config')->middleware('permission:messages.config');
    Route::post('/config', 'xsoft\messages\MainMessageController@configUpdate')->name('configUpdate')->middleware('permission:messages.config');
    Route::post('/toggleChannel', 'xsoft\messages\MainMessageController@toggleChannel')->name('toggleChannel')->middleware('permission:messages.config');
});

resources/views/messages/messagesConfig.blade.php
<section>
    <header>
        <div>
            <span></span>
        </div>
    </header>
    <div>
        <table>
            <thead>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>slug</th>
            <th>value</th>
            <th>extra</th>
            <th></th>
            </thead>
            <tbody>
            <form action="{{route('messages.configUpdate')}}" method="POST">
                @foreach($messageConfigs as $config)
                    <tr>
                        @csrf
                        @method("POST")
                        <td>{{$config->id}}</td>
                        <td>{{$config->name}}</td>
                        <td>{{$config->description}}</td>
                        <td>{{$config->slug}}</td>
                        <td><input name="config[{{$config->slug}}]" value="{{$config->value}}" type="number"
                                   min="{{$min_values[$config->slug]}}" max="{{$max_values[$config->slug]}}">
                        </td>
                        <td>{{$config->extra}}</td>
                        </td>
                        <td>
                            <button type="submit">Save</button>
                        </td>
                    </tr>
                @endforeach
            </form>
            </tbody>
        </table>
    </div>
</section>
<section>
    <header>
        <div>
            <span>Messages channels config</span>
        </div>
    </header>
    <div>
        <table>
            <col width="80%">
            <col width="10%">
            <col width="10%">
            <thead>
            <tr>
                <th>Template</th>
                <th>System</th>
                <th>E-mail</th>
            </tr>
            </thead>
            <tbody>
            @foreach($templates as $template)
                <tr>
                    <td>{{$template->name}}</td>
                    <td>
                        <div>
                            <input class="template_checkbox" type="checkbox" data-type="system"
                                   data-id="{{$template->id}}" {{$template->system ? "checked": ""}}>
                        </div>
                    </td>
                    <td>
                        <div>
                            <input class="template_checkbox" type="checkbox" data-type="email"
                                   data-id="{{$template->id}}" {{$template->email ? "checked": ""}}>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</section>
<script>
    $('.template_checkbox').on("click", function () {
        let url = "{{route('messages.toggleChannel',['messageTemplate'=>'NT_PLACEHOLDER'])}}";
        url = url.replace('NT_PLACEHOLDER', $(this).data('id'));
        $.ajax({
            type: 'POST',
            url: url,
            data: {type: $(this).data('type')},
            success: function (response) {

            }
        });
    })
</script>